### ISSUE TITLE
Include the ExtendedMediaPicker

### ISSUE THREAD

**Issue by kipusoep** [Jeavon/Umbraco-Core-Property-Value-Converters#12]
Hi, great package!

Could you include the [ExtendedMediaPicker](https://github.com/rolfis/ExtendedMediaPicker) inside the MediaPropertyValueConverter too please?

**Comment by Jeavon** [comment]
Thanks, ExtendedMediaPicker isn't a "Core" editor so it wouldn't belong in this package. However it is extremely easy to implement like below:

```
namespace MyProjectNameSpace
{
    using Our.Umbraco.PropertyConverters;
    using Umbraco.Core.Models.PublishedContent;

    public class ExtendedMediaPickerPropertyConverter : MultipleMediaPickerPropertyConverter
    {
        /// <summary>
        /// Reuses the <see cref="Our.Umbraco.PropertyConverters.MultipleMediaPickerPropertyConverter"/> for CTH.ExtendedMediaPicker
        /// </summary>
        /// <param name="propertyType">The Umbraco property type to convert</param>
        /// <returns>A value indicating whether this converter can convert the value</returns>
        public override bool IsConverter(PublishedPropertyType propertyType)
        {
            return propertyType.PropertyEditorAlias.Equals("CTH.ExtendedMediaPicker");
        }
    }
}
```

Either ExtendedMediaPicker should include the converter itself or I suppose we could create a "addon" package for the Core Value Converters for community editors such as this one.......?????

**Comment by kipusoep** [comment]
That's a really nice solution indeed, thanks!
I guess you're right about not being a Core property editor and if it's this easy to add a new property editor alias to an existing converter I suggest to not bother at all :-)
