### ISSUE TITLE
Improve Efficiency of ContentPickerPropertyConverter

### ISSUE THREAD

**Issue by DanDiplo** [Jeavon/Umbraco-Core-Property-Value-Converters#3]
Great project, saved me loads of time! But just wondering, is it necessary in https://github.com/Jeavon/Umbraco-Core-Property-Value-Converters/blob/v2/Our.Umbraco.PropertyConverters/ContentPickerPropertyConverter.cs to instantiate a new `List<string>` every time that `ConvertSourceToObject` is called? Could this list be made static?

**Comment by Jeavon** [comment]
Thanks! Yes, I think it could and should be!

**Comment by Jeavon** [comment]
Done! Will be in the next release

**Comment by DanDiplo** [comment]
Wow, fast work - great stuff!

**Comment by Jeavon** [comment]
I wish I had time to make more efficiencies :) When I have time, I'm hoping to implement some caching of results although this will be taken care of in the Umbraco v8 object cache (that's what GetPropertyCacheLevel is for)....

**Comment by DanDiplo** [comment]
Well, if I spot anything, I'll let you know - if they're small things often quicker than making a pull request.

I confess I never understood what the GetPropertyCacheLevel was for, apart from it wasn't yet implemented. Be cool to see that in action in v8.

**Comment by Jeavon** [comment]
Awesome, I did write documentation, it's here http://our.umbraco.org/documentation/Extending-Umbraco/Property-Editors/value-converters-v7#PropertyValueCacheLevel if your interested :)

**Comment by Jeavon** [comment]
This improvement is included in v2.1.4 released today. Thanks!

**Comment by DanDiplo** [comment]
Excellent, just updated via Nuget today, and all works fantastic. #h5yr
