### ISSUE TITLE
Idea: Override or disable a particular converter?

### ISSUE THREAD

**Issue by tomfulton** [Jeavon/Umbraco-Core-Property-Value-Converters#6]
Occasionally I run into a bug with a converter or just want some different behavior for my situation.  I normally end up having to write some custom extension method and updating my code to use that instead of the value converter syntax.

I was thinking it might be nice to be able to write another value converter instead and disabling the included one, to avoid the need to update all existing code.  The problem is that Umbraco only allows one converter to be registered for a Property Type and won't even start up if it detects more than one.

So, what if we could enable/disable each converter in this package individually?  That would allow devs to take advantage of individual converters in this package without being forced to use them all.

Does this feature make sense?  Would it be as simple as adding a check for a web.config flag in the `IsConverter` methods?

**Comment by Jeavon** [comment]
Hey Tom,
I have thought about it, but then Stephan showed me you can do it already using the application starting event and then your own will take it's place. e.g

```
    protected override void ApplicationStarting(UmbracoApplicationBase umbracoApplication, ApplicationContext applicationContext)
    {
        PropertyValueConvertersResolver.Current.RemoveType<MediaPickerPropertyConverter>();
    }
```

It didn't seem logical to add a disable mechanism (even if it was simpler) when there was one already?

I actually use this method to replace some of the Core converters with my own ones.

What do you think?

J

**Comment by tomfulton** [comment]
Hey Jeavon, perfect!  I was thinking about something like that but wasn't sure it would work and hadn't got around to trying yet.  I think that should work great :+1:
