### ISSUE TITLE
Unable to uninstall 'Microsoft.Net.Http 2.0.20710.0' because 'Microsoft.AspNet.WebApi.Client 4.0.30506.0, UmbracoCms.Core 7.2.1' depend on it.

### ISSUE THREAD

**Issue by pedroadaodev** [Jeavon/Umbraco-Core-Property-Value-Converters#7]
Hi,

I've started a new project in VS 2013, MVC empty project, .net 4.5

With Nuget installed latest version of Umbraco CMS 7.2.1.

After tried to install CoreValueConverters, but this error appears on Manage Nuget Packages
"Unable to uninstall 'Microsoft.Net.Http 2.0.20710.0' because 'Microsoft.AspNet.WebApi.Client 4.0.30506.0, UmbracoCms.Core 7.2.1' depend on it."

Can you help me?

Thank you,
Pedro Adão

**Comment by Jeavon** [comment]
I have tried to recreate  your experience however I do not get any error. In a clean VS solution I install UmbracoCms then Our.Umbraco.CoreValueConverters and there are no errors....?

**Comment by pedroadaodev** [comment]
I'll try again with a new solution. Thanks for your help.

**Comment by pedroadaodev** [comment]
Hi. I've tried with various other instalations of Umbraco and it worked.

In the project that I have this error, I found that it was a VB project. :(
