### ISSUE TITLE
When fetching property from an image i just get the JSON out

### ISSUE THREAD

**Issue by rasmusfjord** [Jeavon/Umbraco-Core-Property-Value-Converters#9]
Hey :)

First of all this only happens on my IIS not when im in VS(IIS Express). Im pulling out the image like this :

```
 IPublishedContent img = lang.logoHeader;
                    <a href="@lang.Url" title="@Umbraco.GetDictionaryValue("Gå til forsiden")">
                        <img src="@img.GetPropertyValue("UmbracoFile")" />
                    </a>
```

On my local machine it works, but i have now copied it to my server and suddenly its just spitting out the raw json and in my log i get this :

```
Could not parse current db value to a JObject. Exception: Newtonsoft.Json.JsonReaderException: Error parsing comment. Expected: *, got m. Path '', line 1, position 1.
   at Newtonsoft.Json.JsonTextReader.ParseComment()
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonTextReader.ReadInternal()
   at Newtonsoft.Json.JsonTextReader.Read()
   at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader)
   at Newtonsoft.Json.Linq.JObject.Parse(String json)
   at Umbraco.Web.PropertyEditors.ImageCropperPropertyValueEditor.ConvertEditorToDb(ContentPropertyData editorValue, Object currentValue)
```

The server is running nothing fancy, but i dunno if its tight to these issues : 
http://issues.umbraco.org/issue/U4-4049
http://issues.umbraco.org/issue/U4-4756

**Comment by Jeavon** [comment]
Hi, firstly this error isn't anything to do with the value converter, it looks like it's working just fine.

Anyhow it looks like you've changed the umbracoFile property from upload to image cropper? You will need to update your Razor to use GetCropUrl. E.g. @img.GetCropUrl()

**Comment by rasmusfjord** [comment]
Hey Jeavon 

First of all thx for answering so fast. The only reason i thought it would be the value converter was that it works fine when images come through the grid. 

I know its not the forum to ask here but maybe you have an idea what this could be then. I think razor is quite up to date, its totally new 7.2.1 solution that is running completely fine on iis express and on a azure website. But when i move it to Microsoft server 2012 it suddenly throws the above. ps. the server already running an umbraco solution. 

Just ignore if you have no idea :)

**Comment by Jeavon** [comment]
It's no problem, did you see my comment above about switching from upload to cropper?

**Comment by rasmusfjord** [comment]
Hey there yea i saw and it is true i have switched to the cropper on UmbracoFile property. I will try to update the server can see there are some .net updates and then i will try to repush the site thank so far.

**Comment by Jeavon** [comment]
Np, this might help you with switching http://our.umbraco.org/projects/collaboration/crop-healer-for-umbraco

**Comment by rasmusfjord** [comment]
Oh nice man will try it out, you just have a tool for everything in that belt dont ya -;)
